server:
  port: 28080
  servlet:
    session:
      timeout: -1
  error:
    include-stacktrace: always
    whitelabel:
      enabled: false
#  ssl:
#    key-store: "classpath:demoKeystore.jks"
#    key-store-password: "Et#170817"
#    key-alias: "myAlias"
      # SSL 적용
      #ssl:
      #  enabled: true
      #  key-alias: alias_name
      #  key-store: classpath:mk.p12
      #  key-store-type: PKCS12
      #  key-store-password: 1q2w3e4r5t

# mybatis  설정
mybatis:
  configuration:
    multiple-result-sets-enabled: false
    jdbc-type-for-null: null      #null
    call-setters-on-nulls: true   # DB 값이 null 일경우 null을 넣어준다 아니면 vo property가 생기지 않아서 에러남
    cache-enabled: false
  mapper-locations:
    - classpath:mybatis/mapper/*.xml

  # jasypt 암호화 설정
jasypt:
  encryptor:
    bean: jasyptStringEncryptor

spring:
  # Spring datasource설정
  # MySQL DB
  #  datasource:
  #      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  #      url: ENC(ffuhdDlmoW+15cX61wrVptTNUsbaHNuWZWfREMRwb3s71pCVkS6zBKv2pcGVsze4hAShmU+h9u4goC6IA26Smav96QJRLvrLg3cBJsbvDaI7qGgrEsQz19R5gPIXQkqfAKQ60+F7Th0R8C6K6Ih8a3y4p05KJmckmE9pNOFR9ak=)
  #      username: ENC(HtP6Vf0hGSQlGur8xLh/MQ==)
  #      password: ENC(3OI2ycy5djrqAd+7m60MpPFY2gedTpVh)

  # Maria DB local
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: ENC(WklP/ZUW7iGrhTU6Zu8CyAge+oHryT7xNiSb5BGbOoDy4kHbf3tQMD+qEIKdmZ6gn1lsHDf6JZvoXid0Nw+Srt/701ghtLONQvfsxru4Lo5nRRQzbD01f+A8+6lK/65WZS5xQJQpPt7rowWugneQ4BvIL4YpgXEesfS4kIVRHUdE0TXnNZGH51ljUv7jUkpv)
    username: ENC(HtP6Vf0hGSQlGur8xLh/MQ==)
    password: ENC(3OI2ycy5djrqAd+7m60MpPFY2gedTpVh)



  # Maria DB
  #  datasource:
  #      driver-class-name: org.mariadb.jdbc.Driver
  #      url: ENC(jwDWe1nhk85wZHcxSMCxdinU2AQWtbcZQTJv6p5c7URODUWGLLowplzvX2VXta2O/3beo+1+t6ATMxevA3t0pi5QykjqCxIcvJo+JUQ6qNSNN67Q665dsMxhGpthk8bZka77P8c3GKKrriJs/vZJoEzYrMWOB92F1Cqe3aB1K8I=)
  #      username: ENC(HtP6Vf0hGSQlGur8xLh/MQ==)
  #      password: ENC(3OI2ycy5djrqAd+7m60MpPFY2gedTpVh)
  # Spring mvc 설정
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp


  # Spring 파일 수정시 자동 리로드 설정
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  freemarker:
    cache: false
  # Spring resources 파일 경로(파일 리로드때문에설정)
  web:
    resources:
      static-locations:
        - classpath:/static/

  config:
    activate:
      on-profile: dev  #현재 사용 하고 싶은 yml 파일명
